include $(SRC_TARGET_DIR)/board/generic_x86_64/BoardConfig.mk

# 4K aligned ~ 200M
BOARD_VENDORIMAGE_PARTITION_SIZE := 209715200

BUILD_EMULATOR_OPENGL := false

BOARD_GPU_DRIVERS := i915 i965 nouveau

BOARD_USES_MINIGBM := true

